export const WWW_RESPONSE_STATUS = {
    STATUS_404: 'STATUS_404',
    STATUS_200: 'STATUS_200',
    STATUS_CANT_CREATE_READ_STREAM: 'STATUS_CANT_CREATE_READ_STREAM'
}

export default WWW_RESPONSE_STATUS
